#!/bin/bash

# setup-vps.sh
# Automated setup script for Justapedia Tools on Ubuntu/Debian VPS

set -e

echo ">>> Updating system..."
sudo apt-get update

echo ">>> Installing dependencies (Node.js, Git, Tor)..."
# Install Node.js 20.x
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs git tor

# Install PM2
echo ">>> Installing PM2..."
sudo npm install -g pm2

echo ">>> Configuring Tor..."
# Ensure Tor is running
sudo service tor start

echo ">>> Setting up environment variables..."

# Check if .env exists, if not create it
if [ ! -f .env ]; then
    echo "Creating .env file..."
    
    echo "----------------------------------------------------------------"
    echo "Please choose your proxy setup:"
    echo "1) Use Tor (Free, but slow and might be blocked)"
    echo "2) Use Custom SOCKS5 Proxy (Paid/Private - Recommended)"
    echo "----------------------------------------------------------------"
    read -p "Enter choice [1/2]: " proxy_choice

    if [ "$proxy_choice" = "1" ]; then
        PROXY_URL="socks5://127.0.0.1:9050"
        echo "Selected Tor. Proxy set to: $PROXY_URL"
    else
        read -p "Enter your SOCKS5 Proxy URL (e.g., socks5://user:pass@host:port): " PROXY_URL
    fi

    cat > .env <<EOL
# Generated by setup-vps.sh
SOCKS_PROXY=$PROXY_URL
PORT=3000
NODE_ENV=production
EOL
    echo ".env created!"
else
    echo ".env already exists. Skipping creation."
fi

echo ">>> Installing project dependencies..."
npm install

echo ">>> Building project..."
npm run build

echo ">>> Starting with PM2..."
pm2 start ecosystem.config.js
pm2 save
pm2 startup | tail -n 1 > /tmp/pm2-startup-cmd.sh
chmod +x /tmp/pm2-startup-cmd.sh
# Execute the command that pm2 startup told us to run (it requires sudo usually, but we are running as user)
# Note: The user might need to run the output of 'pm2 startup' manually if this fails.

echo ">>> Deployment Complete!"
echo "Your app should be running on port 3000."
echo "If you chose Tor, verify that it is working."
